/*indexes*/


CREATE TABLE dbo.bookstore
(book_id   INT NOT NULL, 
 book_name VARCHAR(100)
);
Insert into dbo.bookstore values(1,'Learn ABC of SQL Server')
Insert into dbo.bookstore values(2,'Advanced troubleshooting step SQL Server')


--its better to use ssms gui for creating indexes

--index creatation using tsql

CREATE CLUSTERED INDEX IX_BookID
ON dbo.BookStore(Book_id);
GO


--creating non clustered indexes
CREATE NONCLUSTERED INDEX NCIX_BookID
ON dbo.BookStore(Book_id);



--------------------------------------

--autogenerated clusted index of primary KEY
USE [BANK]
GO

/****** Object:  Index [PK__ACCOUNTS__9F092CAA323BA405]    Script Date: 12-09-2021 09:32:04 ******/
ALTER TABLE [dbo].[ACCOUNTS] ADD PRIMARY KEY CLUSTERED 
(
	[Account_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


---------------------------------------

EXECUTE sp_helpindex employees
--the sp_helpindex all indexes of the table employees

--------------------------------------

SELECT  
    avg_page_space_used_in_percent, 
    avg_fragmentation_in_percent, 
    index_level, 
    record_count, 
    page_count, 
    fragment_count, 
    avg_record_size_in_bytes
FROM sys.dm_db_index_physical_stats(DB_ID('testDB'), OBJECT_ID('bookstore'), NULL, NULL, 'DETAILED');
GO

SELECT * FROM BookStore
