--!**! INDEXES !**!


--1.CLUSTERED INDEX
--2.NONCLUSTERED INDEX

--1.CLUSTERED INDEX
CREATE TABLE DEMOINDEX
(
	ID INT PRIMARY KEY, --default apply a clustered index
	NAME VARCHAR(10),
	ADDRESS VARCHAR(100)
)

--2.NONCLUSTERED INDEX

CREATE NONCLUSTERED INDEX nonclusteredindex_on_JobId
ON Employees (JobId)
