
-- Q1: List Names of Customers who are Depositors and have Same Branch City as that of SUNIL
	
	SELECT DP.Cname FROM Deposit AS DP JOIN BRANCH AS BR ON DP.Bname=BR.BNAME WHERE BR.CITY IN
	(SELECT BR.CITY FROM Deposit AS DP JOIN BRANCH AS BR ON DP.Bname=BR.BNAME WHERE DP.Cname='SUNIL')

	--ANOTHER WAY:-
	SELECT Cname FROM Deposit AS DP
	WHERE Bname IN (SELECT BR.BNAME FROM BRANCH AS BR WHERE BR.CITY = 
	(SELECT CITY FROM BRANCH WHERE BNAME=(SELECT Bname FROM Deposit WHERE Cname='SUNIL')))

--Q2: List All the Depositors Having Depositors Having Deposit in All the Branches where SUNIL is Having Account

	SELECT Cname FROM Deposit WHERE Bname IN (SELECT Bname FROM Deposit WHERE Cname='SUNIL')
	
	--ANOTHER WAY:-
	--IF HERE WE USE BORROW TABLE THEN
	SELECT Cname FROM Deposit WHERE Bname IN (SELECT Bname FROM Deposit WHERE Cname='SUNIL')
	UNION
	SELECT CNAME FROM BORROW WHERE BNAME IN (SELECT BNAME FROM BORROW WHERE CNAME='SUNIL')

--Q3: List the Names of Customers Living in the City where the Maximum Number of Depositors are Located

	SELECT CNAME FROM CUSTOMER WHERE CITY = 
	(SELECT TOP(1) TMP.CITY FROM (SELECT COUNT(BR.CITY) AS Depositor_In_City,BR.CITY FROM Deposit AS DP JOIN BRANCH AS BR ON DP.Bname=BR.BNAME GROUP BY BR.CITY)TMP ORDER BY Depositor_In_City DESC)

--Q4: List Names of Borrowers Having Deposit Amount Greater than 1000 and Loan Amount Greater than 2000

	SELECT BW.CNAME FROM BORROW AS BW WHERE BW.CNAME IN(SELECT DP.Cname FROM Deposit AS DP WHERE DP.Amount >1000)  AND  BW.AMOUNT>2000

	--ANOTHER WAY:-
	SELECT BW.CNAME FROM BORROW AS BW JOIN Deposit AS DP ON BW.CNAME=DP.Cname WHERE DP.Amount > 1000 AND BW.AMOUNT > 2000 

--Q5: List All the Customers Living in NAGPUR and Having the Branch City as MUMBAI or DELHI
	
	SELECT CUS.CNAME FROM CUSTOMER AS CUS WHERE CUS.CITY='NAGPUR' AND CUS.CNAME IN 
	(SELECT DP.Cname FROM Deposit AS DP JOIN BRANCH AS BR ON DP.Bname=BR.BNAME WHERE BR.CITY='MUMBAI' OR BR.CITY='DELHI')

	--ANOTHER WAY:-
	SELECT CUS.CNAME FROM CUSTOMER AS CUS WHERE CUS.CITY='NAGPUR' AND CUS.CNAME IN 
	(SELECT DP.Cname FROM Deposit AS DP WHERE DP.Bname IN (SELECT BR.BNAME FROM BRANCH AS BR WHERE BR.CITY='MUMBAI' OR BR.CITY='DELHI'))

--Q6: Count the Number of Customers Living in the City where Branch is Located

	SELECT COUNT(CUS.CNAME)AS Total_Customers,CUS.CITY  FROM CUSTOMER AS CUS WHERE CUS.CITY IN (SELECT BR.CITY FROM BRANCH AS BR) GROUP BY CUS.CITY
