-----------Day-3-----------
----STRING-FUNCTION
--ASCII FOR 7 BIT
SELECT ASCII('A') as A;
SELECT ASCII('a') as a;

--CHAR-NCHAR-
SELECT NCHAR(65) AS A;
SELECT CHAR (97) AS a;
--BMP CHARACTER
SELECT NCHAR(9835);
SELECT CHAR(9835);

--UNICODE FOR MORE THAN 8 BIT 
SELECT UNICODE('a');

--CHARINDEX
SELECT CHARINDEX('SUNDY',LASTNAME) FROM Employees_1;

SELECT CHARINDEX('GER',FirstName,1) FROM Employees_1;

SELECT CHARINDEX('GAR',FirstName,1) FROM Employees_1;

SELECT CHARINDEX('sundy',LASTNAME) FROM Employees_1;

SELECT CHARINDEX('Sundy',LASTNAME) FROM Employees_1;

SELECT CHARINDEX('Sundy',LASTNAME  COLLATE Latin1_General_CS_AS) FROM Employees_1;

SELECT CHARINDEX('sundy','My name is SUNDY '  COLLATE Latin1_General_CS_AS) FROM Employees_1;

SELECT CHARINDEX('Sundy','My name is SUNDY ') FROM Employees_1;

--CONCAT
SELECT CONCAT(FirstName,' ',LastName) AS FullName FROM Employees;
SELECT CONCAT(FirstName,CHAR(13),LastName) AS FullName FROM Employees;
SELECT CONCAT(NULL,NULL);
--CONCAT_WS
SELECT CONCAT_WS(' ',FirstName,LastName) FROM Employees;
SELECT CONCAT_WS('-',FirstName,LastName) FROM Employees;
SELECT CONCAT_WS('-',FirstName,CHAR(13),LastName) FROM Employees;
SELECT CONCAT_WS('-',NULL,NULL);

--SOUNDEX
SELECT SOUNDEX(FirstName),SOUNDEX(LastName) FROM Employees;
SELECT SOUNDEX(FirstName),SOUNDEX(LastName) FROM Employees_1;
SELECT SOUNDEX(EmployeeID) FROM Employees;

--DIFFERNCE
SELECT DIFFERENCE(FirstName,LastName) FROM Employees;
SELECT DIFFERENCE(FirstName,LastName) FROM Employees_1;

--FORMAT
SELECT FORMAT(HireDate,'D') FROM Employees;
SELECT FORMAT(HireDate,'d') FROM Employees;
SELECT FORMAT(HireDate,'dd/MM/yyyy') FROM Employees;
SELECT FORMAT(Salary,'C','en-in') FROM Employees;
SELECT FORMAT(Salary,'C') FROM Employees;
SELECT FORMAT(cast('07:35' as time), N'hh.mm');
SELECT FORMAT(cast('07:35' as time), N'hh:mm');
SELECT FORMAT(cast('07:35' as time), N'hh\.mm');
SELECT FORMAT(cast('07:35' as time), N'hh\:mm'); 
SELECT FORMAT(SYSDATETIME(), N'hh:mm tt');
select FORMAT(CAST('2018-01-01 01:00' AS datetime2), N'hh:mm tt');
select FORMAT(CAST('2018-01-01 14:00' AS datetime2), N'hh:mm tt');
SELECT FORMAT(SYSDATETIME(), N'HH:mm tt');

--LEFT
SELECT LEFT(FirstName,1) FROM Employees;

--LEN -- DATALENGTH
SELECT LEN(FirstName), DATALENGTH(FirstName) FROM Employees;
SELECT LEN(CONCAT(FirstName,' ', LastName )), DATALENGTH(CONCAT(FirstName,' ', LastName )) FROM Employees;

--LOWER
SELECT LOWER(CONCAT(FirstName,' ',LastName))  FROM Employees;

--LTRIM
SELECT LTRIM('    hELLO MY NAMW IS SANDY');
SELECT '    hELLO MY NAMW IS SANDY';

--PATINDEX
SELECT PATINDEX('%i%',FirstName),FirstName FROM Employees;

SELECT PATINDEX('%[^ a-zA-Z]%',FirstName),FirstName FROM Employees;

--QUOTENAME
SELECT QUOTENAME(FirstName) FROM Employees;

--REPLACE
SELECT REPLACE(FirstName,'ste','Sun'),FirstName FROM Employees
WHERE  FirstName LIKE '%STE%';

--REPLICATE
SELECT REPLICATE('Hi',2) + ' ' + FirstName FROM Employees ;

--reverse
SELECT REVERSE(FirstName),FirstName FROM Employees;

--RIGHT
SELECT RIGHT(FirstName,3) FROM Employees;

--RTRIM
SELECT RTRIM('HI HELLO OR THANK YOU          ');

--SPACE
SELECT FirstName+SPACE(3)+LastName FROM Employees;

--STR
SELECT STR(Salary,4) FROM Employees;
SELECT STR(Salary,4,3) FROM Employees;

--STRING_SPLIT
--//ERROR
SELECT FirstName,value FROM Employees CROSS APPLY string_split(FirstName,'a');

--STUFF
SELECT STUFF(FirstName,2,5,LastName), FirstName,LastName FROM Employees;

--SUBSTRING
SELECT SUBSTRING(FirstName, 2,5), FirstName FROM Employees;

--TRANSLATE
SELECT TRANSLATE(FirstName,'ET','AN') , FirstName FROM Employees;

--TRIM
SELECT TRIM('             HI HELLO THANK U               ');

--UPPER
SELECT UPPER(FirstName) FROM Employees;

----DATE AND TIME FINCTION
--SYSDATETIME
SELECT SYSDATETIME();

--SYSDATETIMEOFFSET
SELECT SYSDATETIMEOFFSET();

--SYSUTCDATETIME
SELECT SYSUTCDATETIME();

--CURRENT_TIMESTAMP
SELECT CURRENT_TIMESTAMP;

--GETDATE
SELECT GETDATE();

--GETUTCDATE
SELECT GETUTCDATE();

--DATENAME
SELECT DATENAME(YEAR,HireDate) ,HireDate from Employees;
SELECT DATENAME(QUARTER,HireDate) ,HireDate from Employees;
SELECT DATENAME(MONTH,HireDate) ,HireDate from Employees;
SELECT DATENAME(DAYOFYEAR,HireDate) ,HireDate from Employees;
SELECT DATENAME(DAY,HireDate) ,HireDate from Employees;
SELECT DATENAME(WEEK,HireDate) ,HireDate from Employees;
SELECT DATENAME(WEEKDAY,HireDate) ,HireDate from Employees;
SELECT DATENAME(HOUR,SYSDATETIME()) from Employees;
SELECT DATENAME(MINUTE,SYSDATETIME()) from Employees;
SELECT DATENAME(SECOND,SYSDATETIME())  from Employees;
SELECT DATENAME(MILLISECOND,SYSDATETIME())  from Employees;
SELECT DATENAME(MICROSECOND,SYSDATETIME())  from Employees;
SELECT DATENAME(NANOSECOND,SYSDATETIME())  from Employees;
SELECT DATENAME(TZOFFSET,SYSDATETIME()) from Employees;
SELECT DATENAME(ISO_WEEK,SYSDATETIME()) from Employees;

--DATEPART
SELECT DATEPART(YEAR,HireDate) ,HireDate from Employees;
SELECT DATEPART(QUARTER,HireDate) ,HireDate from Employees;
SELECT DATEPART(MONTH,HireDate) ,HireDate from Employees;
SELECT DATEPART(DAYOFYEAR,HireDate) ,HireDate from Employees;
SELECT DATEPART(DAY,HireDate) ,HireDate from Employees;
SELECT DATEPART(WEEK,HireDate) ,HireDate from Employees;
SELECT DATEPART(WEEKDAY,HireDate) ,HireDate from Employees;
SELECT DATEPART(HOUR,SYSDATETIME()) from Employees;
SELECT DATEPART(MINUTE,SYSDATETIME()) from Employees;
SELECT DATEPART(SECOND,SYSDATETIME())  from Employees;
SELECT DATEPART(MILLISECOND,SYSDATETIME())  from Employees;
SELECT DATEPART(MICROSECOND,SYSDATETIME())  from Employees;
SELECT DATEPART(NANOSECOND,SYSDATETIME())  from Employees;
SELECT DATEPART(TZOFFSET,SYSDATETIME()) from Employees;
SELECT DATEPART(ISO_WEEK,SYSDATETIME()) from Employees;

--DAY
SELECT DAY(SYSDATETIME()) from Employees;

--MONTH
SELECT MONTH(SYSDATETIME()) from Employees;

--YEAR
SELECT YEAR(SYSDATETIME()) from Employees;

--DATEFROMPARTS
SELECT DATEFROMPARTS('1999','1','14');
SELECT DATEFROMPARTS(1999,1,14);
SELECT DATEFROMPARTS(1999,'1',14);
--DATETIME2FROMPARTS
SELECT DATETIME2FROMPARTS(1999,1,14,14,30,54,50,6);

--DATETIMEFROMPARTS
SELECT DATETIMEFROMPARTS(1999,1,14,14,30,54,50);

--DATETIMEOFFSETFROMPARTS
SELECT DATETIMEOFFSETFROMPARTS(1999,1,14,14,30,54,10,5,40,7);

--SMALLDATETIMEFROMPARTS
SELECT SMALLDATETIMEFROMPARTS(1999,1,14,14,30);

--TIMEFROMPARTS
SELECT TIMEFROMPARTS(14,30,14,500,5);

--DATEDIFF
SELECT DATEDIFF(WEEKDAY,SYSDATETIME(),'1999-01-13');
SELECT DATEDIFF(YEAR,'2025-02-23','1999-01-13');

--DATEDIFF_BIG
SELECT DATEDIFF_BIG(WEEKDAY,SYSDATETIME(),'1999-01-13')
SELECT DATEDIFF_BIG(YEAR,'2025-02-23','1999-01-13');

--DATEADD
SELECT DATEADD(DAY,10,SYSDATETIME());

--EOMONTH
SELECT EOMONTH(SYSDATETIME(),5);

--SWITCHOFFSET
--SELECT SWITCHOFFSET(SYSDATETIMEOFFSET(),'-5:00');

--TODATETIMEOFFSET	
--SELECT TODATETIMEOFFSET	(SYSDATETIME(),'+500');

--DATEFIRST
SET DATEFIRST 5;
SELECT @@DATEFIRST;

SELECT @@DATEFIRST;
--LANGUAGE
SELECT @@LANGUAGE AS 'Language Name';  

SET LANGUAGE Français;
SELECT DATENAME(month, SYSDATETIME()) AS 'Month Name' ; 

SET LANGUAGE us_english;
SELECT DATENAME(month, SYSDATETIME()) AS 'Month Name' ; 
--sp_helplanguage
sp_helplanguage

--ISDATE
SELECT ISDATE(Salary) FROM Employees;

SELECT ISDATE(FirstName) FROM Employees;

SELECT ISDATE(HireDate) FROM Employees;

SELECT ISDATE(SYSDATETIME());
----MATH-FUNCTION
--ABS
SELECT ABS(6.78);

--ACOS
DECLARE @COS FLOAT;
SET @COS = -1.0;
SELECT ACOS(@COS);

--ASIN
DECLARE @SIN FLOAT;
SET @SIN = -1.0;
SELECT ASIN(@SIN);

--ATAN
DECLARE @TAN FLOAT;
SET @TAN = -1.0;
SELECT ASIN(@TAN);

--ATN2
DECLARE @X FLOAT = 1.0, @Y FLOAT = -1.0;
SELECT ATN2(@X, @Y);
 
 --CEILING
 SELECT CEILING($123.55), CEILING(-123.45), CEILING(5.4); 

 --COS
DECLARE @CS FLOAT = 1.0;
SELECT COS(@CS);

 --COT
DECLARE @CT FLOAT = 1.0;
SELECT COT(@CT);

--DEGREES
SELECT DEGREES(PI()/2);

--EXP
SELECT EXP(1);

--FLOOR

SELECT FLOOR(123.45), FLOOR(-123.45), FLOOR($123.65); 

--LOG
SELECT LOG(3);
SELECT LOG(3,2);

--LOG10
SELECT LOG10(3);

--PI
SELECT PI();

--POWER
SELECT POWER(2,4);

--RADIANS
SELECT RADIANS(90);

--RAND
SELECT RAND(90);

--ROUND
SELECT ROUND(123.9994, 10), ROUND(123.9995, 3);  
SELECT ROUND(123.4545, 2), ROUND(123.45, -2); 
SELECT ROUND(5.4445,1), ROUND(5.55,2), ROUND(5.65,2)

--SIGN
SELECT SIGN(-125), SIGN(0), SIGN(564); 

--SIN
SELECT SIN(45.175643);

--SQRT
SELECT SQRT(1.00), SQRT(10.00);

--SQUARE
SELECT SQUARE(4.00), SQUARE(-10.00);

--TAN
SELECT TAN(45.175643);

--SYSTEM-FUNCTION
--PARTITION --Do Not UnderStand
CREATE PARTITION FUNCTION RangePF1 ( INT )  
AS RANGE FOR VALUES (10, 100, 1000) ;   
SELECT $PARTITION.RangePF1 (150) ;  

--ERROR_PROCEDURE
IF OBJECT_ID ( 'usp_ExampleProc', 'P' ) IS NOT NULL   
    DROP PROCEDURE usp_ExampleProc;   
  
-- Create a stored procedure that   
-- generates a divide-by-zero error.  
CREATE PROCEDURE usp_ExampleProc  
AS  
    SELECT 1/0;  
  
BEGIN TRY  
    -- Execute the stored procedure inside the TRY block.  
    EXECUTE usp_ExampleProc;  
END TRY  
BEGIN CATCH  
    SELECT ERROR_PROCEDURE() AS ErrorProcedure;  
END CATCH;  

--@@ERROR  
IF @@ERROR = 347
	BEGIN
	PRINT N'tHIS IS ERROR';
	END

--ERROR_SEVERITY
--ERROR_STATE 
--ERROR_LINE
--ERROR_MESSAGE
--ERROR_NUMBER
BEGIN TRY  
    -- Generate a divide-by-zero error.  
    SELECT 1/0;
END TRY  
BEGIN CATCH  
    SELECT  
        ERROR_NUMBER() AS ErrorNumber,  
        ERROR_SEVERITY() AS ErrorSeverity,  
        ERROR_STATE() AS ErrorState,  
        ERROR_PROCEDURE() AS ErrorProcedure,  
        ERROR_LINE() AS ErrorLine,  
        ERROR_MESSAGE() AS ErrorMessage;  
END CATCH;  
GO  

--@@IDENTITY  
SELECT @@IDENTITY AS 'Identity'; 

--@@PACK_RECEIVED  
SELECT @@PACK_RECEIVED AS 'Packets Received'; 

--FORMATMESSAGE
SELECT FORMATMESSAGE('This is the %s and this is the %s.', 'first variable', 'second variable') 
SELECT FORMATMESSAGE('Signed int %i, %d %i, %d, %+i, %+d, %+i, %+d', 5, -5, 50, -50, -11, -11, 11, 11);
SELECT FORMATMESSAGE('Signed int with up to 3 leading zeros %03i', 5);  
SELECT FORMATMESSAGE('Signed int with up to 20 leading zeros %020i', 5);  
SELECT FORMATMESSAGE('Signed int with leading zero 0 %020i', -55);  
SELECT FORMATMESSAGE('Bigint %I64d', 3000000000);
SELECT FORMATMESSAGE('Unsigned int %u, %u', 50, -50);  
SELECT FORMATMESSAGE('Unsigned octal %o, %o', 50, -50);  
SELECT FORMATMESSAGE('Unsigned hexadecimal %x, %X, %X, %X, %x', 11, 11, -11, 50, -50);  
SELECT FORMATMESSAGE('Unsigned octal with prefix: %#o, %#o', 50, -50);  
SELECT FORMATMESSAGE('Unsigned hexadecimal with prefix: %#x, %#X, %#X, %X, %x', 11, 11, -11, 50, -50);  
SELECT FORMATMESSAGE('Hello %s!', 'TEST');  
SELECT FORMATMESSAGE('Hello %20s!', 'TEST');  
SELECT FORMATMESSAGE('Hello %-20s!', 'TEST');  

--@@ROWCOUNT   ROWCOUNT_BIG
SELECT @@ROWCOUNT;

SELECT ROWCOUNT_BIG();
--GET_FILESTREAM_TRANSACTION_CONTEXT
--//SELECT GET_FILESTREAM_TRANSACTION_CONTEXT();

--@@TRANCOUNT
BEGIN TRAN 
	PRINT @@TRANCOUNT;
SELECT @@TRANCOUNT;

--GETANSINULL
SELECT GETANSINULL();
SELECT GETANSINULL('sandy');

--BINARY_CHECKSUM
SELECT BINARY_CHECKSUM(*) FROM Employees;

--HOST_ID
SELECT HOST_ID();

--CHECKSUM
SELECT CHECKSUM(*) FROM Employees;

--HOST_NAME
SELECT HOST_NAME();

--COMPRESS --DECOMPRESS
SELECT COMPRESS(FirstName) FROM Employees;

--SELECT DECOMPRESS(FirstName) FROM Employees; ONLY FOR MAX DATATYPE


--ISNULL
SELECT ManagerID,ISNULL(ManagerID,'100') FROM Employees;

--CONNECTIONPROPERTY
SELECT   
ConnectionProperty('net_transport')  ,  
ConnectionProperty('protocol_type'), 
ConnectionProperty('local_net_address')  ,  
ConnectionProperty('auth_scheme'), 
ConnectionProperty('local_tcp_port')  ,  
ConnectionProperty('client_net_address'), 
ConnectionProperty('physical_net_transport')  ;

--ISNUMERIC
SELECT ISNUMERIC(Salary) FROM Employees;
SELECT ISNUMERIC(FirstName) FROM Employees;

--CONTEXT_INFO
SET CONTEXT_INFO 45;
SELECT CONTEXT_INFO();

SELECT CONTEXT_INFO();

--CURRENT_REQUEST_ID
SELECT CURRENT_REQUEST_ID();

--MIN_ACTIVE_ROWVERSION
SELECT MIN_ACTIVE_ROWVERSION()

--NEWID
-- Creating a local variable with DECLARE/SET syntax.  
DECLARE @myid uniqueidentifier  
SET @myid = NEWID()  
PRINT 'Value of @myid is: '+ CONVERT(varchar(255), @myid)  

--CURRENT_TRANSACTION_ID  
SELECT CURRENT_TRANSACTION_ID( ) 

--SESSION_CONTEXT(N'key')  
SELECT SESSION_CONTEXT(N'key') ; 
-- Creating a local variable with DECLARE/SET syntax. 
--NEWSEQUENTIALID() --style
--CREATE TABLE myTable (ColumnA uniqueidentifier DEFAULT NEWSEQUENTIALID()); ;

--SESSION_ID ( ) 
SELECT SESSION_USER ;

--XACT_STATE
SELECT XACT_STATE() ;


