--RETURN ABSOLUTE VALUE (POSITIVE)
SELECT ABS(-1)
--RETURN THE ANGLE WHOSE COSINE IS SPECIFIED
SELECT ACOS(-1)
--RETURN THE ANGLE WHOSE SINE IS SPECIFIED
SELECT ASIN(-1)
SELECT ASIN(1)


--RETURN NEAREST GREATER NUMBER
SELECT CEILING(124.5)

--RETURN NEAREST LESSER NUMBER
SELECT FLOOR(122.4)

--RETURN EXPONENTIAL VALUE FOR THE FLOAT NUMBER
SELECT EXP(11.2)

--RETURN THE LOG OF NUMBER
SELECT LOG(2)

SELECT LOG10(2)

--RETURN THE POWER OF NUMBER
SELECT POWER(2,2)

--RETURN SQUARE OF NUMBER
SELECT SQUARE(5)

--RETURN SQUARE ROOT OF NUMBER
SELECT SQRT(100)

SELECT ROUND(125.99578,3)