--RETURN ASCII VALUE FOR PARTICULAR CHARACTER RETURN INT VALUE
SELECT ASCII('a') AS 'a' , ASCII('A') AS 'A'

-- RETURN CHARACTER 
SELECT CHAR(97) 

--UNICODE ITS RETURN THE ASCII VALUE (ASCII FUNCTION IS USED FOR ONLY 7-BIT STREAM)
SELECT UNICODE('æ')

--return the index number of character which we want to find 
SELECT CHARINDEX('a', 'Shreya Thakkar')

SELECT CHARINDEX('a', 'Shreya Thakkar',7)  

SELECT CHARINDEX('A', 'Shreya Thakkar')

--concat the string using concat function

SELECT CONCAT('SHREYA',' ','THAKKAR') AS 'NAME'

SELECT CONCAT_WS('-','SHREYA','THAKKAR') AS 'NAME'

--SOUNDEX CONVERT STRING TO CHARACTER THAT IS BASED ON HOW THE STRING IS SPOKE
--RETURN VARCHAR IF SAME SOUND IS THERE IN STRING IT WILL RETURN SAME SOUNDEX RESULT
SELECT SOUNDEX ('Smith'), SOUNDEX ('Smythe'); 

SELECT SOUNDEX('Green'), SOUNDEX('Greene'), DIFFERENCE('Green','Greene');  

--RETURN LEFT SIDE OF 2 CHARCAHTER FROM STRING
SELECT LEFT('SHREYA',2)

--RETURN RIGHT SIDE OF 2 CHARCAHTER FROM STRING
SELECT RIGHT('THAKKAR',2)

--REMOVE WHITE SPACE FROM LEFT SIDE
SELECT LTRIM('    SHREYA')

--REMOVE WHITE SPACE FROM RIGHT SIDE
SELECT RTRIM('    SHREYA THAKKAR         ')

--LOWER convert UPPER CASE TO LOWER CASE
SELECT LOWER('SHREYA')

--CONVERT LOWER CASE TO UPPER CASE
SELECT UPPER('shreya')

--FIND PATTERN FROM STRING 
SELECT PATINDEX('%re%','shreya thakkar')


--delimited identifier
SELECT QUOTENAME('ABC[] DEF GHI JKL')

--REPLACE THE STRING WITH ANOTHER VALUE
SELECT REPLACE('JAVA LEARNING','JAVA','SQL')

--REVERSE THE STRING
SELECT REVERSE('JAVA')

--RETURN SPACE
SELECT  FIRSTNAME = LTRIM('SHREYA') +  SPACE(2) + ' THAKKAR'

SELECT STR(12.45, 4, 1)


SELECT * FROM HumanResources.Employee
SELECT STRING_AGG(VacationHours,',') 'VACATIONHOUR' FROM HumanResources.Employee GROUP BY VacationHours

SELECT SUBSTRING('SHREYA',2,5)

--SELECT STRING_SPLIT('SHREYA THAKKAR','')
SELECT FORMAT (123456678,'##-###-####')

