
---STRING FUNCTION

SELECT ASCII('ketan')
SELECT CHAR(29)
SELECT CHARINDEX('t','ketan')
SELECT CONCAT('ketan',' ','jambukiya') as MyName
SELECT FORMAT(getdate(),'hh:mm:ss tt MMMM d,yyyy')
SELECT LEFT('ketan',4) 
SELECT LEN('ketan jambukiya')
SELECT LOWER('KETAN')
SELECT LTRIM('hello everyone')
SELECT PATINDEX('%uy%','hello guys good morning')
SELECT REPLACE('kstan','s','e') 
SELECT RTRIM('hello everyone')
SELECT SOUNDEX('T'),SOUNDEX('Tea')  
SELECT SPACE(5)
SELECT STR(205)
SELECT STUFF('hjklo',1,3,'hel')
SELECT SUBSTRING('hello',1,3)  
SELECT REPLICATE('a',15)
SELECT REVERSE('ketan')
SELECT RIGHT('ketan',4) 