Create DATABASE Assignment1

USE Assignment1

CREATE TABLE Departments(
	DepartmentId INT NOT NULL CONSTRAINT PK_DPT PRIMARY KEY IDENTITY(1,1), 
	Dept_Name VARCHAR(30)
)

CREATE TABLE Employees(
	Employee_Id INT NOT NULL CONSTRAINT PK_EMP PRIMARY KEY IDENTITY(1,1), 
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Email VARCHAR(255) NOT NULL CONSTRAINT UQ_Email UNIQUE CONSTRAINT chk_email CHECK(Email LIKE '%_@__%.__%'),
	PhoneNumber NUMERIC(10) NOT NULL CONSTRAINT CHK_Number CHECK(PhoneNumber BETWEEN 1000000000 AND 9999999999),
	Hire_Date DATE NOT NULL,
	Salary MONEY NOT NULL,
	Commission VARCHAR(30) NOT NULL,
	Department_Id INT NOT NULL,
	--CONSTRAINT FK_Job_emp FOREIGN KEY (Job_Id) REFERENCES Jobs(JobId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_dpt_emp FOREIGN KEY (Department_Id) REFERENCES Departments(DepartmentId) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Invenotry(
Car_Id INT NOT NULL CONSTRAINT PK_INV PRIMARY KEY IDENTITY(1,1),
Car_Brand VARCHAR(30) NOT NULL,
Car_Model VARCHAR(50) NOT NULL, 
Price  MONEY NOT NULL, 
Stock INT NOT NULL
)

CREATE TABLE Customer(
	Cust_Id INT NOT NULL CONSTRAINT PK_CUST PRIMARY KEY IDENTITY(1,1), 
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Email VARCHAR(255) NOT NULL CONSTRAINT UQ_Cust_Email UNIQUE CONSTRAINT CHK_Cust_Email CHECK(Email LIKE '%_@__%.__%'),
	PhoneNumber NUMERIC(10) NOT NULL CONSTRAINT CHK_Cust_number CHECK(PhoneNumber BETWEEN 1000000000 AND 9999999999),	
)

CREATE TABLE Sales(
	Sales_id INT NOT NULL CONSTRAINT PK_Sales PRIMARY KEY IDENTITY(1,1),
	Emp_Id  INT NOT NULL,
	Car_ID INT NOT NULL,
	Cust_Id INT NOT NULL,
	Sold_on Date NOT NULL,
	CONSTRAINT FK_emp_sales FOREIGN KEY (Emp_Id) REFERENCES Employees(Employee_Id),
	CONSTRAINT FK_car_sales FOREIGN KEY (Car_ID) REFERENCES Departments(DepartmentId),
	CONSTRAINT FK_cust_sales FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)  
)

ALTER TABLE Sales
DROP CONSTRAINT FK_car_sales 

ALTER TABLE Sales
ADD CONSTRAINT FK_Inv_sales FOREIGN KEY (Car_ID) REFERENCES Invenotry(Car_Id)

ALTER TABLE Employees
ALTER COLUMN Commission VARCHAR(30) NUll

SELECT * FROM Sales

sp_help Sales

sp_help Employees

