CREATE DATABASE Demo

USE Demo

CREATE TABLE Trainee(
	T_ID INT NOT NULL CONSTRAINT pk_trainee PRIMARY KEY IDENTITY(1,1), 
	T_Name VARCHAR(50) NOT NULL CHECK (T_Name NOT LIKE '%[^a-zA-Z]%'),
	Gender VARCHAR(6) CHECK(Gender IN('Male', 'Female')),
	Mobile NUMERIC(10) CHECK(Mobile BETWEEN 1000000000 AND 9999999999) ,
	Email VARCHAR(255) CONSTRAINT t_email UNIQUE CONSTRAINT chk_email CHECK(Email LIKE '%_@__%.__%'),
	Fac_id INT CONSTRAINT FK_id FOREIGN KEY(Fac_id) REFERENCES Faculty(F_ID) ON DELETE CASCADE
)

CREATE TABLE Faculty(
	F_ID INT NOT NULL CONSTRAINT pk_faculty PRIMARY KEY IDENTITY(1,1), 
	F_Name VARCHAR(50) NOT NULL CHECK (F_Name NOT LIKE '%[^a-zA-Z]%'),
)

ALTER TABLE Trainee
ADD F_ID INT 

ALTER TABLE Trainee
Drop F_ID

ALTER TABLE Trainee
ADD CONSTRAINT FK_id FOREIGN KEY(F_ID) REFERENCES Faculty(F_ID) ON DELETE CASCADE


ALTER TABLE Trainee
DROP COLUMN T_Name

DROP TABLE Trainee
DROP TABLE Faculty

INSERT INTO Trainee VALUES('Niraj', 'Male', 7359411074, 'niraj.surati01@gmail.com',1)
INSERT INTO Trainee VALUES('Meet', 'Male', 7172737475, 'meet01@gmail.com',2)
INSERT INTO Trainee VALUES('Sagar', 'Male', 6365646464, 'basag@gmail.com',1)
INSERT INTO Faculty VALUES('Vinod')
INSERT INTO Faculty VALUES('Amit')


SELECT * FROM Trainee
SELECT * FROM Faculty

DELETE FROM Trainee 

TRUNCATE TABLE Trainee
TRUNCATE TABLE Faculty

DROP DATABASE Demo
use master