---------------Day-15---------------
USE SANDY
-------PRACTISE-EXERSICE
--BEGIN-DISTRIBUTED-TRASACTION
BEGIN DISTRIBUTED TRANSACTION;
DELETE Employees
WHERE DepartmentID = '10'

DELETE Departments WHERE 
DepartmentID ='10'

COMMIT TRANSACTION;
GO

--ROLLBACK-TRASLATION
CREATE TABLE ValueTable (id INT);  
BEGIN TRANSACTION;  
       INSERT INTO ValueTable VALUES(1);  
       INSERT INTO ValueTable VALUES(2);  
ROLLBACK;  


--BEGIN-TRANSACTION
--COMMIT-TRANSACTION
BEGIN TRANSACTION T1
DELETE FROM Jobs
WHERE JobId = '101'
COMMIT;
--WITH-MARK
BEGIN TRANSACTION T2 WITH MARK 'Delete Job'
DELETE FROM Jobs
WHERE JobId = '103'
COMMIT TRANSACTION T2;
GO

--SAVE-TRANSACTION
SAVE TRANSACTION;


