

---IF_ELSE
DECLARE @money MONEY
Select @money = SALARY FROM Employee
WHERE EMPLOYEE_ID=5
IF @money between 700000 AND 8500000
PRINT 'salary between  700000 and 850000'
ELSE
PRINT 'salary not between 700000 and 850000 '
GO

---CASE

SELECT EMPLOYEE_ID,LAST_NAME=
CASE LAST_NAME
     WHEN 'jkl' THEN 'JKL'	
	 WHEN 'fgh' THEN 'FGH'
	 WHEN 'ikm' THEN 'IKM'
	 ELSE LAST_NAME
	 END 
FROM Employee
GO

	



----WHILE

DECLARE @NUMBER INT 
SET @NUMBER=1
WHILE ( @NUMBER <= 10)
BEGIN
  PRINT 'The Number is = ' + CONVERT(VARCHAR,@NUMBER)
  IF @NUMBER>=7
  BREAK
  ELSE
    SET @NUMBER  = @NUMBER  + 1
END
GO