USE Assignment2
GO

-- INDEXES

-- CLUSTERD 

DROP TABLE Demo

CREATE TABLE Demo(
		ID INT IDENTITY(1,1)
	,	Name VARCHAR(30)
	, CONSTRAINT PKDemoID PRIMARY KEY(ID)
)
GO

DROP TABLE Demo2

CREATE TABLE Demo2(
		ID INT IDENTITY(1,1)
	,	Name VARCHAR(30)
	, CONSTRAINT PKDemo2ID PRIMARY KEY(ID)
)


SELECT * FROM demo

EXEC SYS.SP_HELPINDEX  @objname = N'dbo.Demo'
GO

CREATE CLUSTERED INDEX IX_DEMO_ID
	ON dbo.Demo(ID)
GO
	
DROP INDEX PKDemoID
	ON Demo

ALTER TABLE DEMO
ADD CONSTRAINT IX_DEMO_ID PRIMARY KEY(ID)

ALTER INDEX IX_DEMO_ID


-- NON

CREATE NONCLUSTERED INDEX IX_DEMO_ID
	ON dbo.Demo(ID)
GO

EXEC SYS.SP_HELPINDEX  @objname = N'dbo.Demo'
GO

EXEC SYS.SP_HELP


--- TRANSACTION

-- Atomocity, Consistency, Isolation, Duratbility

SET IMPLICIT_TRANSACTIONS ON
COMMIT TRANSACTION
SET IMPLICIT_TRANSACTIONS OFF

-- BEGIN, COMMIT, ROLLBACK, SAVE

SELECT * FROM Sys.tables

INSERT INTO Demo VALUES('abcde')
INSERT INTO Demo2 VALUES('abcde')

BEGIN TRANSACTION TrasUpdate
BEGIN TRY

	UPDATE  Demo
	SET Name = 'DEMO'
	WHERE ID = 2

	UPDATE  Demo2
	SET Name = 'demodemodemodemodemodemodemodemodemodemodemodemodemodemodemodemodemodemodemodemo'
	WHERE ID = 2

	COMMIT TRANSACTION  TrasUpdate
	
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION TrasUpdate
	PRINT 'Changes Rollbacked'
END CATCH


SELECT * FROM DEMO
SELECT * FROM DEMO2