SELECT * FROM Employees
--1) Rank functions

SELECT ROW_NUMBER() OVER (ORDER BY MANAGERID ASC ) [Rank],* FROM EMPLOYEES

SELECT RANK() OVER (ORDER BY MANAGERID ASC ) [Rank],* FROM EMPLOYEES

SELECT DENSE_RANK() OVER (ORDER BY MANAGERID ASC) [Rank],* FROM EMPLOYEES

SELECT NTILE(4) OVER (ORDER BY MANAGERID ASC ) [Rank],* FROM EMPLOYEES

SELECT ROW_NUMBER() OVER (PARTITION BY JOBID ORDER BY MANAGERID ASC) [Rank],* FROM EMPLOYEES

SELECT RANK() OVER (PARTITION BY JOBID ORDER BY MANAGERID ASC ) [Rank],* FROM EMPLOYEES

SELECT DENSE_RANK() OVER (PARTITION BY JOBID ORDER BY MANAGERID ASC) [Rank],* FROM EMPLOYEES

SELECT NTILE(4) OVER (PARTITION BY JOBID  ORDER BY MANAGERID ASC ) [Rank],* FROM EMPLOYEES

--2) Aggregate Functions

SELECT ROW_NUMBER() OVER (ORDER BY MANAGERID ASC) [Rank],* FROM Employees 
SELECT COUNT(ManagerID) FROM Employees

SELECT TOP 3 SALARY,EMPLOYEEID FROM Employees

SELECT SUM(SALARY) FROM Employees

SELECT SUM(SALARY) FROM Employees WHERE EMPLOYEEID < 103

SELECT AVG(SALARY) FROM Employees

SELECT AVg(SALARY) FROM Employees WHERE EMPLOYEEID < 103

SELECT MAX(SALARY) FROM Employees

SELECT MAX(SALARY) FROM Employees WHERE EMPLOYEEID < 103

SELECT MIN(SALARY) FROM Employees

SELECT MIN(SALARY) FROM Employees WHERE EMPLOYEEID < 103

--3) GROUP BY FUNCTION

SELECT SUM(SALARY) FROM Employees GROUP BY DepartmentID

SELECT MIN(SALARY) FROM Employees GROUP BY DepartmentID


