--String Function
--(1)ASCII

		SELECT ASCII('b')

--(2)CHAR

	SELECT CHAR(98)	

--(3)CHARINDEX

		SELECT CHARINDEX('T','SQL TUTORIAL')
		SELECT CHARINDEX('T','SQL TUTORIAL',6)

--(4)CONCAT

		SELECT CONCAT('SQL','TUTORIAL')	
		SELECT CONCAT('SQL',SPACE(5),'TUTORIAL')
		SELECT CONCAT('SQL     ','TUTORIAL')
		SELECT CONCAT('SQL','    TUTORIAL')
		SELECT CONCAT('SQL     ','        TUTORIAL')

--(5)FORMAT

		SELECT FORMAT(20210107,'####-##-##')			
		DECLARE @a DATE = GETDATE()
		SELECT FORMAT(@a,'dd-MM-yyyy')
		DECLARE @b DATE = GETDATE()
		SELECT FORMAT(@b,'ddd-MMM-yyyy')
		SELECT FORMAT(911234567899,'+## ##### #####')
--(6)LEFT

		SELECT LEFT('SQL TUTORIAL',5)	

--(7)LEN

		SELECT LEN('SQL TUTORIAL')
			

--(8)LOWER

		SELECT LOWER('SQL TUTORIAL')						

--(9)LTRIM
	
		SELECT LTRIM('                       SQL TUTORIAL')
			
--(10)PATINDEX

			SELECT PATINDEX('%SQL%','SQL TUTORIAL')
			SELECT PATINDEX('%TO%','SQL TUTORIAL')

--(11)REPLACE

			SELECT REPLACE('SQL TUTORIAL','T','S')

--(12)RTRIM

			SELECT RTRIM('SQL TUTORIAL        ')
			
--(13)SOUNDEX

			SELECT SOUNDEX('TEST'),SOUNDEX('TASTE')
			SELECT SOUNDEX('HIDHI'),SOUNDEX('DJHVUDF')

--(14)SPACE

			SELECT SPACE(5)
			SELECT 'SQL'+SPACE(5)+'TUTORIAL'
--(15)STR

		SELECT STR(205.5)
		SELECT STR(205.4)

--(16)STUFF
			SELECT STUFF('SQL TUTORIAL',5,5,'HIII')
			SELECT STUFF('SQL TUTORIAL',5,1,'HIII')
			SELECT STUFF('SQL TUTORIAL',5,3,(SUBSTRING('SQL TUTORIAL',1,3)))
--(17)SUBSTRING

		SELECT SUBSTRING('SQL TUTORIAL',5,8)
	
--(18)TRIM

		SELECT TRIM('         SQL TUTORIAL            ')
--(19)REPLICATE
	
		SELECT REPLICATE('*',14)
		SELECT REPLICATE('SQL TUTORIAL'+SPACE(5),2)

--(20)REVERSE

		SELECT REVERSE('SQL TUTORIAL')

--(21)RIGHT

		SELECT RIGHT('SQL TUTORIAL',8)
		

--(22)UNICODE

		SELECT UNICODE(49)
		SELECT UNICODE(100)

--(23)NCHAR

		SELECT NCHAR(98)

--(24)DIFFERENCE
		
		SELECT DIFFERENCE('duydiuid','eoifoiabc')
		SELECT DIFFERENCE('TASTE','TEST')

--(25)UPPER

		SELECT UPPER('sql tutorial')

--(25)QUOTENAME

		SELECT QUOTENAME('SQL TUTORIAL','()')
		SELECT QUOTENAME('SQL TUTORIAL','{}')
		SELECT QUOTENAME('SQL TUTORIAL','[]')
		SELECT QUOTENAME('SQL TUTORIAL','<>')

--(26)TRANSLATE
		
		SELECT TRANSLATE('SQL TUTORIAL','T','S')
		SELECT TRANSLATE('93939393','9','2')