SELECT * FROM EMPLOYEES

--(1)Write a query to rank employees based on their salary for a month

	SELECT ROW_NUMBER() OVER(ORDER BY SALARY)AS RANK,SALARY FROM EMPLOYEES
	SELECT RANK() OVER(ORDER BY SALARY)AS RANK,SALARY FROM EMPLOYEES
	SELECT DENSE_RANK() OVER(ORDER BY SALARY)AS RANK,SALARY FROM EMPLOYEES

--(2)Select 4th Highest salary from employee table using ranking function

	SELECT * FROM (SELECT DISTINCT DENSE_RANK()OVER(ORDER BY SALARY DESC) AS RANK1,SALARY FROM EMPLOYEES)a WHERE RANK1=4

--(3)Get department, total salary with respect to a department from employee table.

	SELECT DEPARTMENTID,SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENTID

--(4)Get department, total salary with respect to a department from employee table order by total salary descending

	SELECT DEPARTMENTID,SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENTID ORDER BY SUM(SALARY) DESC

	SELECT * FROM(SELECT DEPARTMENTID,SUM(SALARY) AS TOTAL FROM EMPLOYEES GROUP BY DEPARTMENTID)a ORDER BY a.TOTAL DESC

--(5)Get department wise maximum salary from employee table order by salary ascending

	SELECT DEPARTMENTID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENTID ORDER BY MAX(SALARY) ASC
	
	SELECT * FROM (SELECT DEPARTMENTID,MAX(SALARY) AS SALARY1 FROM EMPLOYEES GROUP BY DEPARTMENTID)a ORDER BY SALARY1 ASC

--(6)Get department wise minimum salary from employee table order by salary ascending

	SELECT DEPARTMENTID,MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENTID ORDER BY MIN(SALARY) ASC
	
	SELECT * FROM (SELECT DEPARTMENTID,MIN(SALARY) AS SALARY1 FROM EMPLOYEES GROUP BY DEPARTMENTID)a ORDER BY SALARY1 ASC

--(7)Select department, total salary with respect to a department from employee table where total salary greater than
--50000 order by TotalSalary descending

	SELECT DEPARTMENTID,SUM(SALARY) AS TOTAL FROM EMPLOYEES GROUP BY DEPARTMENTID
	HAVING SUM(SALARY)>5000 ORDER BY SUM(SALARY)DESC 

	SELECT * FROM (SELECT DEPARTMENTID,SUM(SALARY) AS TOTAL FROM EMPLOYEES GROUP BY DEPARTMENTID)a 
	WHERE TOTAL>5000 ORDER BY TOTAL DESC