-- Batch
-- Declare Variable
DECLARE @TEMP VARCHAR(25) 
SELECT @TEMP=FirstName FROM Employees WHERE EmployeeID = 101
PRINT @TEMP

DECLARE @TEMP INT 
SELECT @TEMP=Salary FROM Employees WHERE EmployeeID = 101
PRINT @TEMP

-- Setting values of the variable
DECLARE @TEMP INT 
SELECT @TEMP=MAX(Salary) FROM Employees
PRINT @TEMP

-- If-else
DECLARE @SalaryValue  MONEY
SELECT @SalaryValue = MIN(Salary) FROM Employees
IF @SalaryValue > 5000
	PRINT 'SalaryValue IS GREATER THAN 5000' 
ELSE
BEGIN
PRINT 'SalaryValue IS NOT GREATER THAN 5000'
END
GO

-- Case Statement
SELECT FirstName,EmployeeID = 
CASE EmployeeID
	WHEN 100 THEN 'EMP ID 100'
	WHEN 101 THEN 'EMP ID 101'
	WHEN 102 THEN 'EMP ID 102'
	ELSE 'NOT SPECIFY'
END
FROM Employees
GO

SELECT FirstName,EmployeeID = 
CASE EmployeeID
	WHEN 100 THEN 'EMP ID 100'
	WHEN 101 THEN 'EMP ID 101'
	WHEN 102 THEN 'EMP ID 102'
	ELSE 'NOT SPECIFY'
END
FROM Employees
GO

-- while
DECLARE @TMP INT
DECLARE @FIRSTNAME VARCHAR(20)
SELECT @TMP=EmployeeID FROM Employees
WHILE ( @TMP) < 105
BEGIN
	SELECT @FIRSTNAME=FirstName FROM EmployeeS WHERE EmployeeID = @TMP
	PRINT @FIRSTNAME
	SET @TMP = @TMP + 1
END 
GO

