
select * from Person

BEGIN TRAN

UPDATE Person
SET FirstName='Lucky'
WHERE PersonID =1

SELECT @@TRANCOUNT AS Transactions

COMMIT TRANSACTION

SELECT @@TRANCOUNT AS Transactions

----------SAVE POINT

BEGIN TRAN 

INSERT INTO Person 
VALUES('Mouse', 'Micky','500 South Buena Vista Street, Burbank','California',43)

SAVE TRANSACTION InsertPerson

DELETE FROM Person WHERE PersonID=3

SELECT * FROM Person

ROLLBACK TRANSACTION InsertPerson

COMMIT

SELECT * FROM Person


--------- Transaction on Adventure Work

select * from Person.EmailAddress

BEGIN TRANSACTION Tr1
BEGIN TRY
	UPDATE Person.EmailAddress SET EmailAddress='employee01@gmail.com' WHERE BusinessEntityID=1
	UPDATE Person.PersonPhone SET PhoneNumber=9898980102 WHERE BusinessEntityID=1
	COMMIT TRANSACTION Tr1
	PRINT 'Transaction Completed'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION Tr1
	PRINT 'Transaction Failed'
END CATCH

------ Isolation Level



SET TRANSACTION ISOLATION LEVEL
READ UNCOMMITTED
BEGIN TRANSACTION ToUpdate
BEGIN TRY
	DECLARE @STIME DATETIME, @ETIME DATETIME
	SET @STIME=GETDATE()
	SELECT * FROM HumanResources.Employee WHERE BusinessEntityID IN(3,5,6)
	SET @ETIME=GETDATE()
	SELECT DATEDIFF(SECOND,@STIME,@ETIME) AS TimeDifference
	COMMIT TRANSACTION ToUpdate
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION ToUpdate
	PRINT 'FAILED TO UPDATE'
END CATCH

SELECT * FROM HumanResources.Employee

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION ToUpdate
BEGIN TRY
	DECLARE @STIME DATETIME, @ETIME DATETIME
	SET @STIME=GETDATE()
	SELECT * FROM HumanResources.Employee WHERE BusinessEntityID IN(3,5,6)
	SET @ETIME=GETDATE()
	SELECT DATEDIFF(SECOND,@STIME,@ETIME) AS TimeDifference
	COMMIT TRANSACTION ToUpdate
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION ToUpdate
	PRINT 'FAILED TO UPDATE'
END CATCH


----- Dirty Read -------

SET TRANSACTION ISOLATION LEVEL
READ UNCOMMITTED
BEGIN TRANSACTION ToSelect
BEGIN TRY
	DECLARE @STIME DATETIME, @ETIME DATETIME
	SET @STIME=GETDATE()
	SELECT * FROM HumanResources.Employee WHERE BusinessEntityID IN(1,2)
	SET @ETIME=GETDATE()
	SELECT DATEDIFF(SECOND,@STIME,@ETIME) AS TimeDifference
	COMMIT TRANSACTION ToUpdate
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION ToSelect
	PRINT 'FAILED TO UPDATE'
END CATCH

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION ToSelect
BEGIN TRY
	DECLARE @STIME DATETIME, @ETIME DATETIME
	SET @STIME=GETDATE()
	SELECT * FROM HumanResources.Employee WHERE BusinessEntityID IN(1,2)
	SET @ETIME=GETDATE()
	SELECT DATEDIFF(SECOND,@STIME,@ETIME) AS TimeDifference
	COMMIT TRANSACTION ToUpdate
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION ToSelect
	PRINT 'FAILED TO UPDATE'
END CATCH


