--!**!Assignment Queries!**!

CREATE TABLE SavingAcount
(
	CustomerID INT PRIMARY KEY,
	CustomerName VARCHAR(50),
	Balance INT
)
INSERT INTO SavingAcount
VALUES(1,'Mahesh',100000),
	(2,'Ramesh',200000),
	(3,'Hitesh',300000)
	
CREATE TABLE FixDeposite
(
	CustomerID INT,
	Balance INT,
	FOREIGN KEY (CustomerID) REFERENCES SavingAcount(CustomerID) 
)
INSERT INTO FixDeposite
VALUES(1,50000),
	(3,1000000)


SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION
BEGIN TRY

	UPDATE SavingAcount SET Balance = (SELECT Balance FROM SavingAcount WHERE CustomerID = 1) - 25000 
		WHERE CustomerID = 1

	UPDATE FixDeposite SET Balance = (SELECT Balance FROM FixDeposite WHERE CustomerID = 1) + 25000
		WHERE CustomerID = 1
COMMIT TRANSACTION
PRINT 'TRANSACTION COMMITTED' 
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'TRANSACTION ROLLBACK ' 
END CATCH

SELECT * FROM SavingAcount
SELECT * FROM FixDeposite