----INSERT TRIGGER

CREATE TRIGGER insert_prac
ON Employee
FOR INSERT
AS
   Declare @changedate DATETIME
   SELECT @changedate = JOINING_DATE FROM Inserted
   IF(@changedate != GETDATE())
   BEGIN

   PRINT ' THIS IS NOT CURRENT DATE '
   END


   INSERT INTO Employee VALUES (9,'zen','shine',85000, '2021-05-26' , 'insurance' , 1)


   
---DELETE TRIGEER

  CREATE TRIGGER Delete_parc
  ON Employee
  FOR DELETE 
  AS
  BEGIN
  PRINT 'DELETE SOME DETAIL'
  END


  DELETE FROM Employee WHERE EMPLOYEE_ID=10

---UPDATE TRIGGER
SELECT * FROM Incentives

CREATE TRIGGER update_prac
ON Incentives
FOR UPDATE
AS
IF UPDATE (INCENTIVE_AMOUNT)
BEGIN
DECLARE @AMOUNT MONEY
SELECT @AMOUNT = INCENTIVE_AMOUNT
FROM Incentives
IF ((@AMOUNT)>6500)
BEGIN
PRINT 'amount is greater than avg amount'
IF ((@AMOUNT)<6500)
PRINT 'amount is less than avg amount'
END
END


UPDATE Incentives SET INCENTIVE_AMOUNT=5000 WHERE EMPLOYEE_REF_ID=1

----AFTER TRIGGER

 CREATE TRIGGER after_parc
  ON Incentives
  AFTER DELETE 
  AS
  BEGIN
  PRINT 'DELETE SOME DETAIL'
  END


DELETE FROM Incentives WHERE INCENTIVE_AMOUNT=6000


----INSTEAD TRIGGER



CREATE TRIGGER instead_prac
ON Incentives
INSTEAD OF  INSERT
AS
   Declare @IntAmt MONEY
   SELECT @IntAmt = INCENTIVE_AMOUNT FROM inserted
   IF(@IntAmt > AVG(@IntAmt))
   BEGIN
   PRINT ' AMOUNT IS GREATER THAN AVG AMOUNT '
   IF(@IntAmt < AVG(@IntAmt))
   BEGIN
   PRINT ' AMOUNT IS LESS THAN AVG AMOUNT '
   END
   END

  INSERT INTO Incentives VALUES (4,GETDATE(),6000)

----

  CREATE TRIGGER instead_delet_parc
  ON Incentives
  INSTEAD OF  DELETE 
  AS
  BEGIN
  PRINT 'DELETE TABLE DETAIL'
  END

  DELETE FROM Incentives WHERE EMPLOYEE_REF_ID=4



  -----ALTER TRIGGER



  ALTER TRIGGER Delete_parc
  ON Employee
  FOR DELETE 
  AS
  BEGIN
  PRINT 'DELETE SOME TABLE DETAIL'
  END


  DELETE FROM Employee WHERE EMPLOYEE_ID=10


----DELETE TRIGGER


  CREATE TRIGGER Delete_parctice
  ON Employee
  FOR DELETE 
  AS
  BEGIN
  PRINT 'DELETE SOME DETAIL'
  END


  DROP TRIGGER Delete_parctice