export interface IStudent {
    firstName: string
    middleName: string
    lastName: string
    birthDate: Date
    birthPlace: string
    firstLanguage: string
    phone: number
    addressLine1: string
    addressLine2: string
    pinCode: number
    cityId: number
    fatherFirstName: string
    fatherMiddleName: string
    fatherLastName: string
    fatherEmail: string
    fatherEducation: string
    fatherProfession: string
    fatherDesignation: string
    fatherPhone: number
    motherFirstName: string
    motherMiddleName: string
    motherLastName: string
    motherEmail: string
    motherEducation: string
    motherProfession: string
    motherDesignation: string
    motherPhone: number
    emergencyContacts: any[]
    referenceDetails: any[]
}