---------------DAY-13---------------
--------PRACTICE-EXERSICE
USE SANDY

--CREATE-FUNCTION
CREATE FUNCTION EMPID(@Empid int)
RETURNS INT
AS
BEGIN 
DECLARE @SALARY INT;
SELECT @SALARY = SUM(Salary) FROM Employees EMP
WHERE EMP.EmployeeID = @Empid;
IF (@SALARY IS NULL)
	SET @SALARY = 0
	RETURN @SALARY;
END;

SELECT EmployeeID,DBO.EMPID(EMPLOYEES.EmployeeID)AS TOTALSALARY FROM Employees
WHERE EmployeeID BETWEEN 101 AND 120;


--TABLE-FUNCTION
CREATE FUNCTION EMPTABLE(@EMPID INT)
RETURNS TABLE
AS 
RETURN
(
SELECT (EMP.FirstName+' '+EMP.LastName) FULLNAME,EMP.Email,EMP.Salary,DEP.DepartmentName,LOC.City FROM (Employees EMP JOIN Departments AS DEP ON  EMP.DepartmentID = DEP.DepartmentID)
JOIN master.DBO.Locations AS LOC ON DEP.LocationID = LOC.LocationID
WHERE EMP.EmployeeID = @EMPID
);

SELECT * FROM EMPTABLE(101)

--CREATE-TABLE-FUNCTION-WITH-MULTIPLE-PARAMETER
CREATE FUNCTION EMPINFO(@EMPID INT)
RETURNS @EMPTable TABLE
(
EmployeeId INT PRIMARY KEY,
FULLNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(25),
SALARY INT,
DEPARTMENT VARCHAR(25),
CITY VARCHAR(25)
)
AS
BEGIN
WITH EMP_TAB(EmployeeID,FULLNAME,Email,Salary,DepartmentName,City)
AS
(
SELECT EMP.EmployeeID, (EMP.FirstName+' '+EMP.LastName) AS FULLNAME,EMP.Email,EMP.Salary,DEP.DepartmentName,LOC.City FROM (Employees EMP JOIN Departments AS DEP ON  EMP.DepartmentID = DEP.DepartmentID)
JOIN master.DBO.Locations AS LOC ON DEP.LocationID = LOC.LocationID
)
INSERT @EMPTable 
SELECT EmployeeID,FULLNAME,Email,Salary,DepartmentName,City FROM EMP_TAB 
RETURN END;
GO

SELECT * FROM EMPTABLE(120)

