USE Practice

--Implicit and Explicit Transaction

SELECT * FROM Employees


SET IMPLICIT_TRANSACTIONS ON
	UPDATE Employees SET Email=FirstName WHERE EmployeeID=103
	UPDATE Employees SET Salary+=500 WHERE EmployeeID=103
	COMMIT TRANSACTION


SET IMPLICIT_TRANSACTIONS ON
	UPDATE Employees SET Email=LastName WHERE EmployeeID=103
	UPDATE Employees SET Salary+=500 WHERE EmployeeID=103
	ROLLBACK TRANSACTION



SELECT * FROM Employees


SET IMPLICIT_TRANSACTIONS OFF
	BEGIN TRANSACTION TR1
		BEGIN TRY
			UPDATE Employees SET FirstName='TestName' WHERE EmployeeID=103
			UPDATE Employees SET EmployeeID=104 WHERE EmployeeID=103
			COMMIT TRANSACTION TR1

		END TRY

		BEGIN CATCH
			ROLLBACK TRANSACTION
			PRINT 'EmployeeId Can not be Duplicate'
		END CATCH


SET IMPLICIT_TRANSACTIONS OFF
	BEGIN TRANSACTION TR1
		BEGIN TRY
			UPDATE Employees SET FirstName='TestFName' WHERE EmployeeID=103
			UPDATE Employees SET LastName='TestLName' WHERE EmployeeID=103
			COMMIT TRANSACTION TR1
			SAVE TRANSACTION TR1
		END TRY

		BEGIN CATCH
			ROLLBACK TRANSACTION TR1
			PRINT 'EmployeeId Can not be Duplicate'

		END CATCH


